// src/components/react/mobileMenu.tsx
import { useState, type ReactNode } from 'react'
import {
  Bars3Icon as MenuIcon,
  XMarkIcon as CloseIcon,
} from '@heroicons/react/24/solid'
import { MobileMenuContainer } from './docsMobileNav'
import { SocialLinksBlock } from './footer'

export function MobileMenu({ children }: { children: ReactNode }) {
  const [isOpen, setIsOpen] = useState(false)

  const handleMenuClick = () => {
    setIsOpen((prevIsOpen) => !prevIsOpen)
  }

  return (
    <>
      <button
        className="px-2 py-1 dark:hover:text-white transition-colors"
        aria-labelledby="Menu"
        onClick={handleMenuClick}
      >
        {isOpen ? (
          <CloseIcon className="w-[22px] text-black dark:text-white" />
        ) : (
          <MenuIcon className="w-[22px]" />
        )}
      </button>
      <MobileMenuContainer
        id="mobile-menu-container"
        isOpen={isOpen}
        onClose={() => setIsOpen(false)}
      >
        {children}
        <SocialLinksBlock className="justify-center" />
      </MobileMenuContainer>
    </>
  )
}

// websites/shared/theme/components/MobileMenu.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { useRoute } from 'vitepress'
import { Bars3Icon as MenuIcon, XMarkIcon as CloseIcon } from '@heroicons/vue/24/solid'
import MobileMenuContainer from './MobileMenuContainer.vue'

const isOpen = ref(false)
const route = useRoute()

watch(
  () => route.path,
  () => {
    isOpen.value = false
  },
)
</script>

<template>
  <button
    class="px-2 py-1 hover:text-white transition-colors"
    aria-labelledby="Menu"
    @click="isOpen = !isOpen"
  >
    <CloseIcon v-if="isOpen" class="w-[22px] text-white" />
    <MenuIcon v-else class="w-[22px]" />
  </button>
  <MobileMenuContainer
    id="mobile-menu-container"
    :is-open="isOpen"
    @close="isOpen = false"
  >
    <slot />
  </MobileMenuContainer>
</template>
