// websites/mswjs.io/src/components/react/avatar.tsx
import type { ReactNode } from 'react'
import { cls } from '../../utils/cls'

interface Props {
  url: string
  className?: string
  name: string
  children: ReactNode
}

export function Avatar({ url, name, children, className }: Props): JSX.Element {
  return (
    <div className="inline-flex items-center gap-3">
      <img
        src={url}
        alt={name}
        className={cls('p-1 border-4 border-stone-700 rounded-full', className)}
      />
      <div>
        <p className="font-semibold leading-5 mb-1.5 text-white">{name}</p>
        <p className="text-neutral-400 leading-5">{children}</p>
      </div>
    </div>
  )
}

// websites/mswjs.io/.vitepress/theme/components/Avatar.vue
<script setup lang="ts">
defineProps<{
  url: string
  name: string
  className?: string
}>()
</script>

<template>
  <div class="inline-flex items-center gap-3">
    <img
      :src="url"
      :alt="name"
      :class="['p-1 border-4 border-stone-700 rounded-full', className]"
    />
    <div>
      <p class="font-semibold leading-5 mb-1.5 text-white">{{ name }}</p>
      <p class="text-neutral-400 leading-5"><slot /></p>
    </div>
  </div>
</template>
