// websites/shared/theme/content/PageCard.vue
<script setup lang="ts">
import { computed, type Component } from 'vue'
import { iconRegistry } from './iconRegistry'

const props = defineProps<{
  url: string
  title: string
  description?: string
  /**
   * Name of an icon in the icon registry, e.g.
   * "CubeTransparentIcon" or "solid/ServerIcon".
   */
  icon?: string
}>()

const isExternal = computed(() => {
  return !props.url.startsWith('/')
})

const iconComponent = computed<Component | undefined>(() => {
  return props.icon ? iconRegistry[props.icon] : undefined
})
</script>

<template>
  <a
    :href="url"
    :target="isExternal ? '_blank' : undefined"
    :rel="isExternal ? 'noopener noreferrer' : undefined"
    class="block my-5 px-5 py-4 border border-neutral-800 rounded-lg shadow-sm text-white no-underline bg-opacity-40 bg-neutral-800 hover:bg-opacity-70"
  >
    <article class="flex items-start gap-5">
      <div class="bg-primary bg-opacity-10 rounded-md p-2">
        <component
          :is="iconComponent"
          v-if="iconComponent"
          class="w-[24px] h-[24px] text-primary text-lg"
        />
      </div>
      <div>
        <p class="mt-0 mb-1 text-base font-bold">{{ title }}</p>
        <p class="mb-0 mt-0 text-sm leading-5 text-neutral-400">
          {{ description || url }}
        </p>
      </div>
    </article>
  </a>
</template>

// websites/mswjs.io/src/components/react/pageCard.tsx
interface PageCardProps {
  url: string
  title: string
  description: string
  icon: React.FC<any>
}

export function PageCard({
  url,
  icon: Icon,
  title,
  description,
}: PageCardProps) {
  const isExternal = !url.startsWith('/')
  const extraProps = isExternal
    ? {
        target: '_blank',
        rel: 'noopener noreferrer',
      }
    : {}

  return (
    <a
      {...extraProps}
      href={url}
      className="block my-5 px-5 py-4 border border-neutral-800 rounded-lg shadow-sm text-white no-underline bg-opacity-40 bg-neutral-800 hover:bg-opacity-70"
    >
      <article className="flex items-start gap-5">
        <div className="bg-primary bg-opacity-10 rounded-md p-2">
          <Icon className="w-[24px] h-[24px] text-primary text-lg" />
        </div>
        <div>
          <p className="mt-0 mb-1 text-base font-bold">{title}</p>
          <p className="mb-0 mt-0 text-sm leading-6 text-neutral-400">
            {description || url}
          </p>
        </div>
      </article>
    </a>
  )
}
