// src/components/react/ads.tsx
import { useState } from 'react'
import { Warning } from './warning'

export function Ads({
  url,
}: {
  // Treat the URL as the unique "key" to trigger
  // re-render across view transitions.
  url: string
}) {
  const [displayWarning, setDisplayWarning] = useState(false)

  console.log('ads render', url)

  return (
    <div key={url}>
      <script
        async
        src="https://media.ethicalads.io/media/client/ethicalads.min.js"
        onAbort={() => console.log('ABORT')}
        onLoad={() => {
          console.log('script loaded!')
        }}
        onError={() => {
          setDisplayWarning(true)
        }}
      ></script>
      <div
        className="horizontal dark flat"
        data-ea-publisher="mswjsio"
        data-ea-type="text"
      />
      {displayWarning ? (
        <div id="adblocker-warning" style={{ display: 'none' }}>
          <Warning>
            <strong>Please allow ads on this website.</strong> Thank you.
          </Warning>
        </div>
      ) : null}
    </div>
  )
}

// .vitepress/theme/docs/Ads.vue
<script setup lang="ts">
import { onMounted, ref, watchEffect } from 'vue'
import { useData } from 'vitepress'

defineProps<{
  publisher: string
}>()

const { isDark } = useData()
const adElement = ref<HTMLDivElement>()
const isAdBlockerDetected = ref(false)

onMounted(() => {
  // Toggle the class directly since the ad client
  // adds its own classes to this element.
  watchEffect(() => {
    adElement.value?.classList.toggle('dark', isDark.value)
  })

  const script = document.createElement('script')
  script.async = true
  script.src = 'https://media.ethicalads.io/media/client/ethicalads.min.js'
  script.onerror = () => {
    isAdBlockerDetected.value = true
  }
  document.head.appendChild(script)
})
</script>

<template>
  <div id="ethical-container">
    <div
      ref="adElement"
      class="horizontal flat"
      :data-ea-publisher="publisher"
      data-ea-type="text"
    />
    <div v-if="isAdBlockerDetected" id="adblocker-warning">
      <div class="warning custom-block">
        <p>
          <strong>Please consider disabling AdBlocker for this site.</strong>
          Thank you for supporting the project.
        </p>
      </div>
    </div>
  </div>
</template>
