// websites/shared/theme/components/SponsorLink.vue
<script setup lang="ts">
import { HeartIcon } from '@heroicons/vue/24/solid'
</script>

<template>
  <a
    href="https://github.com/sponsors/mswjs"
    class="inline-flex items-center px-3 py-1 h-[36px] space-x-1 border rounded-md border-primary text-primary hover:bg-primary hover:text-black"
    target="_blank"
    rel="noopener noreferrer"
  >
    <span class="self-center">
      <HeartIcon class="absolute w-3 motion-safe:animate-ping duration-long" />
      <HeartIcon class="w-3" />
    </span>
    <span class="hidden md:inline">Sponsor</span>
  </a>
</template>

// websites/shared/components/react/sponsorLink.tsx
import { HeartIcon } from '@heroicons/react/24/solid'
import { LinkExternal } from './linkExternal'

export function SponsorLink() {
  return (
    <LinkExternal
      href="https://github.com/sponsors/mswjs"
      className="inline-flex items-center px-3 py-1 h-[36px] space-x-1 border rounded-md border-primary text-primary hover:bg-primary hover:text-black"
    >
      <span className="self-center">
        <HeartIcon className="absolute w-3 motion-safe:animate-ping duration-long" />
        <HeartIcon className="w-3" />
      </span>
      <span className="hidden md:inline">Sponsor</span>
    </LinkExternal>
  )
}
